
### Get Token
POST http://{{hostUrl}}/admin/system/index/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
        client.test("Request executed successfully", function() {
          client.assert(response.status === 200, "Response status is not 200");
        })
        client.global.set("auth_token", response.body.data.token)
 %}

### Get User List
GET http://{{hostUrl}}/admin/system/sysUser/1/10
Authorization: Bearer {{auth_token}}
